USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS dbt_dev_role;

SHOW USERS;

GRANT ROLE dbt_dev_role TO USER FREDRIK_USER;
GRANT ROLE dbt_dev_role TO USER THORBJORN_USER;
GRANT ROLE dbt_dev_role TO USER frey;